name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@1.11
    - name: Check some things
      run: echo "$PWD" && ls -lha
    - name: Build Jar
      run: ./mill foo.assembly && ./mill show foo.assembly
    - name: Upload Jar Artifact
      uses: actions/upload-artifact@v3
      with:
        name: foo-jar-file
        path: ./out/foo/assembly/dest/out.jar
        retention-days: 1
  
  build-alpine:
    needs: [build]
    name: Build Alpine Image
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Repo
      uses: actions/checkout@v3
    -
      name: Download JAR artifact
      uses: actions/download-artifact@v3
      with:
        name: foo-jar-file
    -
      name: Show file?
      run: ls -lha
    -
      name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    # -
    #   name: Build the Docker image
    #   run: docker build . --file Dockerfile.alpine --tag ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:ALPINE-CI-${GITHUB_RUN_NUMBER}
    # -
    #   name: Tag image as latest
    #   run: docker tag ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:ALPINE-CI-${GITHUB_RUN_NUMBER} ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:alpine-latest
    # -
    #   name: Push the Docker image with version number
    #   run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:ALPINE-CI-${GITHUB_RUN_NUMBER}
    # -
    #   name: Update / Push Docker image with latest tag
    #   run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:alpine-latest

    -
      name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:ALPINE-CI-${GITHUB_RUN_NUMBER},${{ env.IMAGE_NAME }}:alpine-latest
        file: ./Dockerfile.alpine
        cache-from: type=gha
        cache-to: type=gha,mode=max
